In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/Users/jidekickpush/Downloads/investments_VC.csv',encoding='ISO-8859-1')

In [3]:
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,"40,000",operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,"15,00,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df.columns=[i.strip(' ') for i in df.columns]

In [5]:
df.shape

(54294, 39)

permalink                  /organization/004-technologies
name                                     004 Technologies
homepage_url            http://004gmbh.de/en/004-interact
category_list                                  |Software|
market                                          Software
funding_total_usd                                    -
status                                          operating
country_code                                          USA
state_code                                             IL
region                              Springfield, Illinois
city                                            Champaign
funding_rounds                                          1
founded_at                                     2010-01-01
founded_month                                     2010-01
founded_quarter                                   2010-Q1
founded_year                                         2010
first_funding_at                               2014-07-24
last_funding_at                                2014-07-24
seed                                                    0
venture                                                 0
equity_crowdfunding                                     0
undisclosed                                             0
convertible_note                                        0
debt_financing                                          0
angel                                                   0
grant                                                   0
private_equity                                          0
post_ipo_equity                                         0
post_ipo_debt                                           0
secondary_market                                        0
product_crowdfunding                                    0
round_A                                                 0
round_B                                                 0
round_C                                                 0
round_D                                                 0
round_E                                                 0
round_F                                                 0
round_G                                                 0
round_H                                                 0
Name: 8, dtype: object

In [7]:
df.columns

Index(['permalink', 'name', 'homepage_url', 'category_list', 'market',
       'funding_total_usd', 'status', 'country_code', 'state_code', 'region',
       'city', 'funding_rounds', 'founded_at', 'founded_month',
       'founded_quarter', 'founded_year', 'first_funding_at',
       'last_funding_at', 'seed', 'venture', 'equity_crowdfunding',
       'undisclosed', 'convertible_note', 'debt_financing', 'angel', 'grant',
       'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding', 'round_A', 'round_B',
       'round_C', 'round_D', 'round_E', 'round_F', 'round_G', 'round_H'],
      dtype='object')

In [8]:
df.round_H.isna().sum()

4856

In [9]:
'''name= ('seed', 'venture', 'equity_crowdfunding',
       'undisclosed', 'convertible_note', 'debt_financing', 'angel', 'grant',
       'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding', 'round_A', 'round_B',
       'round_C', 'round_D', 'round_E', 'round_F', 'round_G', 'round_H')
definition=('Seed rounds are among the first rounds of funding a company will receive, generally while the company is young and working to gain traction',
           'investment from a venture capital firm and describes Series A, Series B, and later rounds',
           'platforms allow individual users to invest in companies in exchange for equity',
           'anonymous investment',
           'â€˜in-betweenâ€™ round funding to help companies hold over until they want to raise their next round of funding',
           'investor lends money to a company, and the company promises to repay the debt with added interest',
           'small round designed to get a new company off the ground. Investors in an angel round include individual angel investors, angel investor groups, friends, and family',
           'company, investor, or government agency provides capital to a company without taking an equity stake in the company',
           'round leds by a private equity firm or a hedge fund and is a late stage round',
           'firms invests in a company after the company has already gone public',
           'firms loans a company money after the company has already gone public',
           'investor purchases shares of stock in a company from other, existing shareholders rather than from the company directly, and it occurs after the company has already gone public',
           'a company will provide its product, which is often still in development, in exchange for capital',
           )
col_def_dict=dict(zip(name,definition))'''

"name= ('seed', 'venture', 'equity_crowdfunding',\n       'undisclosed', 'convertible_note', 'debt_financing', 'angel', 'grant',\n       'private_equity', 'post_ipo_equity', 'post_ipo_debt',\n       'secondary_market', 'product_crowdfunding', 'round_A', 'round_B',\n       'round_C', 'round_D', 'round_E', 'round_F', 'round_G', 'round_H')\ndefinition=('Seed rounds are among the first rounds of funding a company will receive, generally while the company is young and working to gain traction',\n           'investment from a venture capital firm and describes Series A, Series B, and later rounds',\n           'platforms allow individual users to invest in companies in exchange for equity',\n           'anonymous investment',\n           'â€˜in-betweenâ€™ round funding to help companies hold over until they want to raise their next round of funding',\n           'investor lends money to a company, and the company promises to repay the debt with added interest',\n           'small round designed to get a new company off the ground. Investors in an angel round include individual angel investors, angel investor groups, friends, and family',\n           'company, investor, or government agency provides capital to a company without taking an equity stake in the company',\n           'round leds by a private equity firm or a hedge fund and is a late stage round',\n           'firms invests in a company after the company has already gone public',\n           'firms loans a company money after the company has already gone public',\n           'investor purchases shares of stock in a company from other, existing shareholders rather than from the company directly, and it occurs after the company has already gone public',\n           'a company will provide its product, which is often still in development, in exchange for capital',\n           )\ncol_def_dict=dict(zip(name,definition))"

In [10]:
#col_def_df=pd.DataFrame.from_dict(col_def_dict,orient = 'index',columns=['definitions'])

In [11]:
#col_def_df

In [12]:
df.shape

(54294, 39)

In [13]:
def prel_cleqan(df):
    df=df.dropna(how='all')
    df.columns=df.columns.str.strip()
    return df
df=prel_cleqan(df)

In [14]:
df.shape

(49438, 39)

In [15]:
def categ_list(df):
    x=df.category_list.replace(np.nan,'NAN').str.strip('|').str.replace('|',',').str.strip(',').to_list()
    x2=[','.join(i) for i in x]
    df.category_list=pd.DataFrame(x2)
    return df
categ_list(df)

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,"E,n,t,e,r,t,a,i,n,m,e,n,t,,,P,o,l,i,t,i,c,s,,,...",News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,"G,a,m,e,s",Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,"P,u,b,l,i,s,h,i,n,g,,,E,d,u,c,a,t,i,o,n",Publishing,"40,000",operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,"E,l,e,c,t,r,o,n,i,c,s,,,G,u,i,d,e,s,,,C,o,f,f,...",Electronics,"15,00,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,"T,o,u,r,i,s,m,,,E,n,t,e,r,t,a,i,n,m,e,n,t,,,G,...",Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49433,/organization/zzish,Zzish,http://www.zzish.com,"A,n,a,l,y,t,i,c,s,,,G,a,m,i,f,i,c,a,t,i,o,n,,,...",Education,"3,20,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49434,/organization/zznode-science-and-technology-co...,ZZNode Science and Technology,http://www.zznode.com,"E,n,t,e,r,p,r,i,s,e, ,S,o,f,t,w,a,r,e",Enterprise Software,"15,87,301",operating,CHN,NaN,Beijing,...,0.0,0.0,1587301.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49435,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,"W,e,b, ,D,e,v,e,l,o,p,m,e,n,t,,,A,d,v,e,r,t,i,...",Web Development,"97,398",operating,HRV,NaN,Split,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49436,/organization/a-list-games,[a]list games,http://www.alistgames.com,"G,a,m,e,s",Games,"93,00,000",operating,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49437,/organization/x,[x+1],http://www.xplusone.com/,"E,n,t,e,r,p,r,i,s,e, ,S,o,f,t,w,a,r,e",Enterprise Software,"4,50,00,000",operating,USA,NY,New York City,...,0.0,0.0,16000000.0,10000000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
df['funding_total_usd']=df['funding_total_usd'].apply(lambda x: x.replace(',',''))

In [17]:
df.dtypes

permalink                object
name                     object
homepage_url             object
category_list            object
market                   object
funding_total_usd        object
status                   object
country_code             object
state_code               object
region                   object
city                     object
funding_rounds          float64
founded_at               object
founded_month            object
founded_quarter          object
founded_year            float64
first_funding_at         object
last_funding_at          object
seed                    float64
venture                 float64
equity_crowdfunding     float64
undisclosed             float64
convertible_note        float64
debt_financing          float64
angel                   float64
grant                   float64
private_equity          float64
post_ipo_equity         float64
post_ipo_debt           float64
secondary_market        float64
product_crowdfunding    float64
round_A                 float64
round_B                 float64
round_C                 float64
round_D                 float64
round_E                 float64
round_F                 float64
round_G                 float64
round_H                 float64
dtype: object

In [18]:
#df['funding_total_usd']=df['funding_total_usd'].astype('int')

In [19]:
#change data type for float columns:
change_type=['funding_rounds','seed', 'venture', 'equity_crowdfunding',
       'undisclosed', 'convertible_note', 'debt_financing', 'angel', 'grant',
       'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding', 'round_A', 'round_B',
       'round_C', 'round_D', 'round_E', 'round_F', 'round_G', 'round_H']
df[change_type] = df[change_type].astype('int64')

In [20]:
df.dtypes

permalink                object
name                     object
homepage_url             object
category_list            object
market                   object
funding_total_usd        object
status                   object
country_code             object
state_code               object
region                   object
city                     object
funding_rounds            int64
founded_at               object
founded_month            object
founded_quarter          object
founded_year            float64
first_funding_at         object
last_funding_at          object
seed                      int64
venture                   int64
equity_crowdfunding       int64
undisclosed               int64
convertible_note          int64
debt_financing            int64
angel                     int64
grant                     int64
private_equity            int64
post_ipo_equity           int64
post_ipo_debt             int64
secondary_market          int64
product_crowdfunding      int64
round_A                   int64
round_B                   int64
round_C                   int64
round_D                   int64
round_E                   int64
round_F                   int64
round_G                   int64
round_H                   int64
dtype: object

In [21]:
df

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,"E,n,t,e,r,t,a,i,n,m,e,n,t,,,P,o,l,i,t,i,c,s,,,...",News,1750000,acquired,USA,NY,New York City,...,0,0,0,0,0,0,0,0,0,0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,"G,a,m,e,s",Games,4000000,operating,USA,CA,Los Angeles,...,0,0,0,0,0,0,0,0,0,0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,"P,u,b,l,i,s,h,i,n,g,,,E,d,u,c,a,t,i,o,n",Publishing,40000,operating,EST,NaN,Tallinn,...,0,0,0,0,0,0,0,0,0,0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,"E,l,e,c,t,r,o,n,i,c,s,,,G,u,i,d,e,s,,,C,o,f,f,...",Electronics,1500000,operating,GBR,NaN,London,...,0,0,0,0,0,0,0,0,0,0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,"T,o,u,r,i,s,m,,,E,n,t,e,r,t,a,i,n,m,e,n,t,,,G,...",Tourism,60000,operating,USA,TX,Dallas,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49433,/organization/zzish,Zzish,http://www.zzish.com,"A,n,a,l,y,t,i,c,s,,,G,a,m,i,f,i,c,a,t,i,o,n,,,...",Education,320000,operating,GBR,NaN,London,...,0,0,0,0,0,0,0,0,0,0
49434,/organization/zznode-science-and-technology-co...,ZZNode Science and Technology,http://www.zznode.com,"E,n,t,e,r,p,r,i,s,e, ,S,o,f,t,w,a,r,e",Enterprise Software,1587301,operating,CHN,NaN,Beijing,...,0,0,1587301,0,0,0,0,0,0,0
49435,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,"W,e,b, ,D,e,v,e,l,o,p,m,e,n,t,,,A,d,v,e,r,t,i,...",Web Development,97398,operating,HRV,NaN,Split,...,0,0,0,0,0,0,0,0,0,0
49436,/organization/a-list-games,[a]list games,http://www.alistgames.com,"G,a,m,e,s",Games,9300000,operating,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
49437,/organization/x,[x+1],http://www.xplusone.com/,"E,n,t,e,r,p,r,i,s,e, ,S,o,f,t,w,a,r,e",Enterprise Software,45000000,operating,USA,NY,New York City,...,0,0,16000000,10000000,0,0,0,0,0,0

In [22]:
def sum_frame_by_column(df, new_col_name, list_of_cols_to_sum):
    df[new_col_name] = df[list_of_cols_to_sum].astype(int).sum(axis=1)
    return df
df=sum_frame_by_column(df, 'Total_rounds', ['round_A', 'round_B',
       'round_C', 'round_D', 'round_E', 'round_F', 'round_G', 'round_H']);

In [23]:
def sum_frame_by_column(df, new_col_name, list_of_cols_to_sum):
    df[new_col_name] = df[list_of_cols_to_sum].astype(int).sum(axis=1)
    return df
df=sum_frame_by_column(df, 'Total_fund_outsourced', ['venture', 'equity_crowdfunding',
       'undisclosed', 'convertible_note', 'debt_financing', 'angel', 'grant',
       'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding']);

In [24]:
df.loc[8]

permalink                   /organization/004-technologies
name                                      004 Technologies
homepage_url             http://004gmbh.de/en/004-interact
category_list                              S,o,f,t,w,a,r,e
market                                           Software
funding_total_usd                                     -
status                                           operating
country_code                                           USA
state_code                                              IL
region                               Springfield, Illinois
city                                             Champaign
funding_rounds                                           1
founded_at                                      2010-01-01
founded_month                                      2010-01
founded_quarter                                    2010-Q1
founded_year                                          2010
first_funding_at                                2014-07-24
last_funding_at                                 2014-07-24
seed                                                     0
venture                                                  0
equity_crowdfunding                                      0
undisclosed                                              0
convertible_note                                         0
debt_financing                                           0
angel                                                    0
grant                                                    0
private_equity                                           0
post_ipo_equity                                          0
post_ipo_debt                                            0
secondary_market                                         0
product_crowdfunding                                     0
round_A                                                  0
round_B                                                  0
round_C                                                  0
round_D                                                  0
round_E                                                  0
round_F                                                  0
round_G                                                  0
round_H                                                  0
Total_rounds                                             0
Total_fund_outsourced                                    0
Name: 8, dtype: object

In [25]:
df.Total_fund_outsourced==df.funding_total_usd

0        False
1        False
2        False
3        False
4        False
         ...
49433    False
49434    False
49435    False
49436    False
49437    False
Length: 49438, dtype: bool

In [ ]:
#do not work cause we can not rely on those value, column fundings_rounds is better
#def sum_frame_by_column(df, new_col_name, list_of_cols_to_count):
#    df[new_col_name] = (df[list_of_cols_to_count].count(axis=1))
#    return df
#df=sum_frame_by_column(df, 'Number_rounds', ['round_A', 'round_B',
#       'round_C', 'round_D', 'round_E', 'round_F', 'round_G', 'round_H']);

In [ ]:
pd.options.display.max_columns=50

In [ ]:
df.head(-70)

In [ ]:
df.dtypes

In [ ]:
df[['seed','funding_rounds','funding_total_usd','Total_rounds','Total_fund_outsourced']] .head(40)

In [36]:
df.loc[8]

permalink                   /organization/004-technologies
name                                      004 Technologies
homepage_url             http://004gmbh.de/en/004-interact
category_list                              S,o,f,t,w,a,r,e
market                                           Software
funding_total_usd                                     -
status                                           operating
country_code                                           USA
state_code                                              IL
region                               Springfield, Illinois
city                                             Champaign
funding_rounds                                           1
founded_at                                      2010-01-01
founded_month                                      2010-01
founded_quarter                                    2010-Q1
founded_year                                          2010
first_funding_at                                2014-07-24
last_funding_at                                 2014-07-24
seed                                                     0
venture                                                  0
equity_crowdfunding                                      0
undisclosed                                              0
convertible_note                                         0
debt_financing                                           0
angel                                                    0
grant                                                    0
private_equity                                           0
post_ipo_equity                                          0
post_ipo_debt                                            0
secondary_market                                         0
product_crowdfunding                                     0
round_A                                                  0
round_B                                                  0
round_C                                                  0
round_D                                                  0
round_E                                                  0
round_F                                                  0
round_G                                                  0
round_H                                                  0
Total_rounds                                             0
Total_fund_outsourced                                    0
Name: 8, dtype: object

In [ ]:
#The origin of the found for a start-up is come from different outsource and from different rounds of call money, this diversity make the tracking of the investment vs the rounds too fastidious

In [ ]:
#def dup(df,name):
#    df_dup=pd.DataFrame
#    lst=df[df.name.duplicates()].name.to_list()
#    for i in lst:
#        df_dup=df_dup.append(df.loc[df.name==i])
#    return df_dup

In [ ]:
df= df.drop(['permalink'], axis=1)

In [25]:
df.founded_at.isna().sum()

10884

In [33]:
df.founded_at.str.strip()[4]

'2014-01-01'

In [44]:
df.founded_at.unique

<bound method Series.unique of 0        2012-06-01
1               NaN
2        2012-10-26
3        2011-04-01
4        2014-01-01
            ...
49433    2013-01-28
49434           NaN
49435    2012-05-13
49436           NaN
49437    1999-01-01
Name: founded_at, Length: 49438, dtype: object>

In [26]:
df.founded_month.isna().sum()

10956

In [36]:
df.founded_year.isna().sum()

10956

In [48]:
df.founded_year.unique

<bound method Series.unique of 0        2012.0
1           NaN
2        2012.0
3        2011.0
4        2014.0
          ...
49433    2013.0
49434       NaN
49435    2012.0
49436       NaN
49437    1999.0
Name: founded_year, Length: 49438, dtype: float64>

In [49]:
df.founded_year.isna().sum()

10956

In [ ]:
df['category_list'] = df['category_list'].str.split('|')

In [32]:
df['check_value'] = np.where(df['funding_total_usd'] ==df['funding_total_usd'] , 'child', df['sex'])
df.funding_total_usd.isna().count()

49438